version: '3'
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - '8945:8945'
    volumes:
      - /mnt/raid6/pinchflat:/config
      - /mnt/raid6/media_share/Series:/downloads
