services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/raid6/sabnzbd:/config/sabnzbd
      - /mnt/raid6/media_share/Downloads/incomplete:/incomplete-downloads #optional
      - /mnt/raid6/media_share/Downloads:/downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
